<figure>
    <center> <img src="./images/Lecture 5 Exercise.PNG"  alt='missing' width="1100"  ><center/>
<figure/>

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# from sklearn.linear_model import LinearRegression
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [53]:
data = pd.read_csv('Data Sets Lecture 5 Exercise CODEBASICS.csv')
data

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [54]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [60]:
x = data[['Car Model','Mileage','Age(yrs)']].values
y = data['Sell Price($)'].values
print(type(x))

<class 'numpy.ndarray'>


In [61]:
print(x)
print(y)

[['BMW X5' 69000 6]
 ['BMW X5' 35000 3]
 ['BMW X5' 57000 5]
 ['BMW X5' 22500 2]
 ['BMW X5' 46000 4]
 ['Audi A5' 59000 5]
 ['Audi A5' 52000 5]
 ['Audi A5' 72000 6]
 ['Audi A5' 91000 8]
 ['Mercedez Benz C class' 67000 6]
 ['Mercedez Benz C class' 83000 7]
 ['Mercedez Benz C class' 79000 7]
 ['Mercedez Benz C class' 59000 5]]
[18000 34000 26100 40000 31500 29400 32000 19300 12000 22000 20000 21000
 33000]


In [62]:
ohe = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder = 'passthrough')

In [63]:
x = ohe.fit_transform(x)
x

array([[0.0, 1.0, 0.0, 69000, 6],
       [0.0, 1.0, 0.0, 35000, 3],
       [0.0, 1.0, 0.0, 57000, 5],
       [0.0, 1.0, 0.0, 22500, 2],
       [0.0, 1.0, 0.0, 46000, 4],
       [1.0, 0.0, 0.0, 59000, 5],
       [1.0, 0.0, 0.0, 52000, 5],
       [1.0, 0.0, 0.0, 72000, 6],
       [1.0, 0.0, 0.0, 91000, 8],
       [0.0, 0.0, 1.0, 67000, 6],
       [0.0, 0.0, 1.0, 83000, 7],
       [0.0, 0.0, 1.0, 79000, 7],
       [0.0, 0.0, 1.0, 59000, 5]], dtype=object)

In [64]:
X = x[:,1:]

In [66]:
X

array([[1.0, 0.0, 69000, 6],
       [1.0, 0.0, 35000, 3],
       [1.0, 0.0, 57000, 5],
       [1.0, 0.0, 22500, 2],
       [1.0, 0.0, 46000, 4],
       [0.0, 0.0, 59000, 5],
       [0.0, 0.0, 52000, 5],
       [0.0, 0.0, 72000, 6],
       [0.0, 0.0, 91000, 8],
       [0.0, 1.0, 67000, 6],
       [0.0, 1.0, 83000, 7],
       [0.0, 1.0, 79000, 7],
       [0.0, 1.0, 59000, 5]], dtype=object)

In [67]:
model = linear_model.LinearRegression()

In [69]:
model.fit(X,y)

LinearRegression()

In [70]:
model.coef_

array([-4.28466659e+03,  2.45354074e+03, -3.70122094e-01, -1.33245363e+03])

In [71]:
model.predict([[0,1,45000,4]])

array([36991.31721062])