In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
# from sklearn.linear_model import LinearRegression
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [30]:
df  = pd.read_csv("Data Sets Lecture 5 Code basics.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [31]:
dummies= pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [32]:
merged= pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [33]:
data = merged.drop(['town','west windsor'],axis='columns')
data

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [34]:
# input data : x
# x = data.drop(['price'],axis='columns')
x= data[['area','monroe township','robinsville']]
# output data  : y
y = data.price

In [35]:
model = linear_model.LinearRegression()

In [36]:
model.fit(x,y)

LinearRegression()

In [37]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [38]:
model.intercept_

249790.36766292527

In [39]:
# FInd the price on 2800 sqrft home in robinsville

model.predict([[2800,0,1]])

array([590775.63964739])

In [40]:
# FInd the price on 3400 sqrft home in west windsor

model.predict([[3400,0,0]])

array([681241.66845839])

In [41]:
model.score(x,y)

0.9573929037221872

#### This same thing can easily be done with One Hot Encoder

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# Creating LabelEncoder class object

In [43]:
dfle = df
dfle.town = le.fit_transform(df['town'])
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [44]:
# Creating inputs

x= dfle[['town','area']].values
x

y = dfle['price'].values

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer




##### we’re specifying that only the first column has to be transformed. We’re also making sure that the remainder columns are passed through without any changes.
                ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')
                #                                   ^^^^^
                #                                 Tuples

In [46]:
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('town', OneHotEncoder(), [0])])

In [47]:
x = ct.fit_transform(x)
X = x[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [48]:
model.fit(X,y)

LinearRegression()

In [49]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [50]:
model.predict([[0,1,3400]])

array([681241.6684584])