# Lecture 2 : Exercise _ Multiple Linear Regression
<figure>
    <center> <img src="./images/excercise 2.PNG"  style="width:1000px;height:200px;" ></center>
</figure>


In [30]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
import math
from word2number import w2n

In [31]:
df = pd.read_csv('Data Sets  Lecture 2 Exercise Code Basics.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [32]:
df.fillna({
    'experience':'zero',
    'test_score(out of 10)': math.floor(df['test_score(out of 10)'].median())
},inplace=True)

In [33]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [34]:
# for converting experiences string to no
df.experience = df.experience.apply(w2n.word_to_num)

In [35]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [36]:
model = linear_model.LinearRegression()

In [37]:
x= df[['experience','test_score(out of 10)','interview_score(out of 10)']]
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [38]:
y = df['salary($)']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [39]:
model.fit(x,y)

LinearRegression()

In [40]:
model.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [41]:
model.intercept_

17737.263464337688

<figure>
    <center> <img src="./images/excercise q.PNG"  style="width:1000px;height:200px;" ></center>
</figure>


In [44]:
y_cape_1 = model.predict([[2,9,6]])
y_cape_1

array([53205.96797671])

In [46]:
y_cape_2 = model.predict([[12,10,10]])
y_cape_2

array([92002.18340611])